dist: xenial
language: cpp
compiler: gcc
os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      
script:
  - export CC=gcc-8
  - export CXX=g++-8
  - cmake --version
  - cmake -D BUILD_TESTS=ON -S .
  - cmake --build .
  - ctest -V

