dist: xenial
language: cpp
compiler: gcc
os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      
install:
  - |-
      case $TRAVIS_OS_NAME in
        linux)
          DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
          mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
          travis_retry wget --no-check-certificate https://www.cmake.org/files/v3.14/cmake-3.14.0-Linux-x86_64.tar.gz
          tar -xvf cmake-3.14.0-Linux-x86_64.tar.gz > /dev/null
          mv cmake-3.14.0-Linux-x86_64 cmake-install
          PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
          cd ${TRAVIS_BUILD_DIR}
          ;;
      esac        
      
script:
  - export CC=gcc-8
  - export CXX=g++-8
  - cmake --version
  - cmake -B build
  - cmake --build build
  - cd build
  - ctest -V     
